version: '3'
services:
  magenta:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:6666"
    container_name: 'magenta-docker'
    tty: true
    volumes:
      - ./workspace:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all